//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarCode_MVC4.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BarCodeEntities : DbContext
    {
        public BarCodeEntities()
            : base("name=BarCodeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ClearInventory> ClearInventory { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<HistoryInventory> HistoryInventory { get; set; }
        public virtual DbSet<ImportInventory> ImportInventory { get; set; }
        public virtual DbSet<Note> Note { get; set; }
        public virtual DbSet<PackagingMaterial> PackagingMaterial { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Srnm> Srnm { get; set; }
        public virtual DbSet<Staff> Staff { get; set; }
        public virtual DbSet<TempInventory> TempInventory { get; set; }
        public virtual DbSet<Zone> Zone { get; set; }
        public virtual DbSet<FunctionList> FunctionList { get; set; }
        public virtual DbSet<Staff_View> Staff_View { get; set; }
        public virtual DbSet<ClearInventory_View> ClearInventory_View { get; set; }
        public virtual DbSet<HistoryInventory_View> HistoryInventory_View { get; set; }
        public virtual DbSet<ImportInventory_View> ImportInventory_View { get; set; }
        public virtual DbSet<Inventory> Inventory { get; set; }
        public virtual DbSet<Inventory_View> Inventory_View { get; set; }
        public virtual DbSet<APKFile> APKFile { get; set; }
        public virtual DbSet<SysPara> SysPara { get; set; }
    }
}
