//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarCode_MVC4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FunctionList
    {
        public string NodeID { get; set; }
        public string ParentID { get; set; }
        public string NodeText { get; set; }
        public Nullable<int> NodeSequence { get; set; }
        public string NodeURL { get; set; }
        public string FunctionID { get; set; }
        public string Description { get; set; }
    }
}
