//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarCode_MVC4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportInventory
    {
        public string Type { get; set; }
        public string Prod { get; set; }
        public string Thickness { get; set; }
        public string Widt { get; set; }
        public Nullable<int> Leng { get; set; }
        public string Splice { get; set; }
        public string Ptno { get; set; }
        public Nullable<System.DateTime> ProductDate { get; set; }
        public string CustomerNO { get; set; }
        public string PackNo { get; set; }
        public string StaffID { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string SrnmType { get; set; }
        public string CtlNo1 { get; set; }
        public string CtlNo2 { get; set; }
        public Nullable<double> NewWeight { get; set; }
        public Nullable<double> GrossWeight { get; set; }
        public string ZoneSN { get; set; }
        public string ZoneID { get; set; }
        public string Thickness2 { get; set; }
    }
}
